# Generated by Django 4.2.3 on 2023-09-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='paid_status',
        ),
    ]
